spring.application.name=personalised-storybook-core

spring.ai.gemini.api-key=${GEMINI_API_KEY}
spring.ai.gemini.model=gemini-2.5-flash
spring.ai.gemini.project-id=gen-lang-client-0149166558

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.project-id=gen-lang-client-0149166558

spring.ai.openai.api-key=${OPENAI_API_KEY}

chat.model=gemini

server.port=${PORT:8080}