package com.fusion.psb.config;

public class StorybookConstants {

  public static final String HARCODED_STORY_CONTENT = "## Jarnav and the Ramnavmi Rainbow Spark!\n"
      + "\n"
      + "**Storybook Title:** Jarnav and the Ramnavmi Rainbow Spark!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 1: Illustration - Jarnav, a lively 4-year-old with bright eyes and a ready smile, is running through a vibrant Indian street decorated for Ramnavmi. Marigold garlands hang everywhere, and colorful lanterns glow. He's wearing a festive kurta and looks full of energy.)**\n"
      + "\n"
      + "Jarnav, with your quick feet and strong little legs, the world was always an exciting place! Especially today, on Ramnavmi! The air in India hummed with joy. Sweet smells of ladoos and incense filled your nose, and the sound of joyful songs and little drums made your heart thump-thump-thump!\n"
      + "\n"
      + "You zoomed past shimmering silk banners and jumped over the shadows of glowing lanterns. Your athletic body was always ready for an adventure!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 2: Illustration - Jarnav is standing near a large, beautifully decorated rangoli design on the ground. A tiny, golden, shimmering spark lifts off the rangoli and floats towards him, twinkling playfully.)**\n"
      + "\n"
      + "As you paused for a moment, catching your breath near a giant, colorful rangoli design, something incredible happened! A tiny, golden spark, no bigger than your thumbnail, lifted right off the ground! It wasn't a firefly, it was too bright, too shimmery! It danced in the air, twinkling like a mini-star, and then… it winked at you!\n"
      + "\n"
      + "It spun in a dizzying circle, then floated a little further away, as if saying, \"Follow me, Jarnav!\"\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 3: Illustration - Jarnav, eyes wide with wonder, is following the golden spark. The spark leads him down a narrow, slightly overgrown path that seems to glow faintly. He's nimble, easily stepping over roots and small plants.)**\n"
      + "\n"
      + "\"Whoa!\" you whispered, your eyes wide with wonder. This was no ordinary spark! Your athletic feet knew exactly what to do. You took off, following the little golden light. It led you away from the busy street, down a narrow, winding path you’d never noticed before.\n"
      + "\n"
      + "The path itself seemed to glow faintly, like it was sprinkled with stardust! You hopped over a root, ducked under a low-hanging branch, and your heart pounded with happy excitement. Where was this magical spark taking you?\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 4: Illustration - The path opens into a hidden grove. The trees have leaves that glow in different colors. Floating orbs of light drift gently. The golden spark hovers over a shimmering, almost translucent waterfall, which flows into a pool of glowing water.)**\n"
      + "\n"
      + "Suddenly, the path opened up! You gasped. You had found a secret grove! The trees here weren't green; their leaves shimmered in shades of ruby red, emerald green, and sapphire blue! Floating orbs of light drifted gently between them, like sleepy bubbles.\n"
      + "\n"
      + "The golden spark zoomed ahead, stopping over a waterfall that wasn't made of water, but of pure, shimmering light! It cascaded into a pool that glowed with all the colors of a rainbow.\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 5: Illustration - The golden spark zips into the shimmering waterfall. As it does, the waterfall ripples, and a magnificent, glowing peacock with emerald feathers and ruby-red eyes steps out from behind it, spreading its tail. Jarnav looks amazed.)**\n"
      + "\n"
      + "The tiny golden spark zipped right into the shimmering waterfall! *Whoosh!* The light-water rippled and swirled. And then, from behind the glowing curtain, stepped the most magnificent creature you had ever seen!\n"
      + "\n"
      + "It was a peacock, but not just any peacock! Its feathers were made of pure, glowing emerald, and its eyes sparkled like ruby gems. It arched its neck, unfurled its giant, shimmering tail, and let out a soft, musical call. It was the Peacock of Ramnavmi Radiance!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 6: Illustration - Jarnav, full of energy, mimics the peacock's movements. The peacock seems to be playing a game, leading Jarnav through the glowing grove. They are surrounded by magical plants and flowers that sparkle.)**\n"
      + "\n"
      + "The glowing peacock looked at you, then dipped its head, as if inviting you to play. It took a few graceful steps, then turned its head, looking back. \"Are you ready, Jarnav?\" its eyes seemed to say.\n"
      + "\n"
      + "You didn't need to be told twice! With a burst of your athletic energy, you ran after it, jumping over glowing moss and weaving through plants that sparkled like tiny diamonds. The peacock led you on a joyful chase, its luminous tail fanning out as it glided through the magical grove. You felt like you could run forever!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 7: Illustration - The peacock leads Jarnav to a clearing where many other tiny, golden sparks are scattered like fallen stars. Jarnav, with his quick hands and agile movements, begins to gather them, putting them into a magical, glowing basket that appears next to him.)**\n"
      + "\n"
      + "The peacock finally stopped in a clearing bathed in soft, rainbow light. And there, scattered all around, were hundreds of tiny golden sparks, just like the one that led you here! They twinkled on the glowing leaves, sat on rainbow-colored flowers, and even floated gently in the air.\n"
      + "\n"
      + "The peacock nudged a small, glowing basket that shimmered into existence beside you. \"These are the scattered joys of Ramnavmi,\" its eyes seemed to tell you. \"Gather them, brave Jarnav!\"\n"
      + "\n"
      + "With your quick hands and agile body, you began to scoop up the sparks. They felt warm and buzzy in your palms, giggling as they flew into the basket. You darted here, zoomed there, your athletic spirit making the task exciting and fun!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 8: Illustration - Jarnav, with a full, glowing basket, stands next to the peacock. He lifts the basket high. As he does, all the sparks fly out and shoot up into the sky, creating a dazzling fireworks display of golden light and rainbow colors.)**\n"
      + "\n"
      + "Soon, the basket was full, overflowing with happy, golden sparks! You lifted it high, your strong little arms holding it steady. The glowing peacock let out a triumphant call.\n"
      + "\n"
      + "And then, *WHOOSH!* All the sparks zoomed out of the basket! They shot up into the sky, swirling and dancing! They exploded into a dazzling fireworks display of pure golden light and every color of the rainbow! The sky above the secret grove glittered and sparkled, painting everything in magical hues. It was the most beautiful, exciting light show you had ever seen!\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 9: Illustration - The grove is now bathed in the afterglow of the fireworks. Jarnav is smiling, full of joy and wonder. The peacock bows its head gently. The golden spark from the beginning reappears and floats gently back towards Jarnav, landing softly in his hand.)**\n"
      + "\n"
      + "The dazzling light slowly faded, leaving the grove bathed in a soft, magical afterglow. You clapped your hands, your heart bursting with joy and wonder. The glowing peacock bowed its magnificent head, a silent thank you.\n"
      + "\n"
      + "And then, the very first golden spark, the one that had led you on this amazing adventure, appeared again. It floated gently down, landing softly in your open palm. It wasn't just a spark anymore; it was a tiny, warm glow, like a secret memory of your incredible journey.\n"
      + "\n"
      + "---\n"
      + "\n"
      + "**(Page 10: Illustration - Jarnav is back in his bed, fast asleep, with a faint, golden glow coming from his closed hand under the blanket. The room is dark, but the glow hints at the magic he experienced. A small, framed picture of a peacock is on his bedside table.)**\n"
      + "\n"
      + "The glowing peacock watched as the path back home shimmered open. With one last look at the magical grove, you ran back, your athletic body feeling light and happy.\n"
      + "\n"
      + "You tumbled into your bed, the tiny, warm glow still nestled safely in your hand. You closed your eyes, and in your dreams, you were still running, jumping, and playing with the glowing peacock, under a sky filled with Ramnavmi Rainbow Sparks.\n"
      + "\n"
      + "What an exciting Ramnavmi adventure, Jarnav! And it was all thanks to your brave heart and quick feet!";

}
